<?php
use App\Models\{MedicalCase,Patient,Doctor,User,DoctorVisit,Setting};
use App\Support\{AccessScope,Money};
use App\Enums\Permission;
use App\Services\FinancialReport;
use Livewire\Attributes\{Computed,Title};
use Livewire\Component;
new #[Title('لوحة التحكم')] class extends Component {
    #[\Livewire\Attributes\Url] public string $branch='';
    public function boot(): void { abort_unless(auth()->user()->isStaff() && auth()->user()->hasPermission(Permission::ViewCases),403); }
    private function query() { return AccessScope::cases(auth()->user())->when($this->branch,fn($q)=>$q->where('branch_id',$this->branch)); }
    #[Computed] public function stats(): array {
        $q=$this->query();
        return ['today'=>(clone $q)->whereDate('exam_date',today())->count(),'total'=>(clone $q)->count(),'month'=>(clone $q)->whereBetween('exam_date',[today()->startOfMonth()->toDateString(),today()->endOfMonth()->toDateString()])->count(),'new'=>(clone $q)->where('workflow_status','new')->count(),'in_progress'=>(clone $q)->where('workflow_status','in_progress')->count(),'completed'=>(clone $q)->where('workflow_status','completed')->count(),'incomplete'=>(clone $q)->whereDoesntHave('files',fn($q)=>$q->where('storage_status','ready'))->count(),'unopened'=>(clone $q)->whereHas('files',fn($q)=>$q->where('storage_status','ready'))->whereNull('first_opened_at')->count(),'patients'=>AccessScope::patients(auth()->user())->when($this->branch,fn($q)=>$q->whereHas('branches',fn($b)=>$b->where('branches.id',$this->branch)))->count(),'doctors'=>AccessScope::doctors(auth()->user())->active()->when($this->branch,fn($q)=>$q->whereHas('branches',fn($b)=>$b->where('branches.id',$this->branch)))->count(),'users'=>User::when(!auth()->user()->isAdmin(),fn($q)=>$q->whereIn('branch_id',AccessScope::branchIds(auth()->user())))->when($this->branch,fn($q)=>$q->where('branch_id',$this->branch))->count()];
    }
    #[Computed] public function recentCases() { return $this->query()->with(['patient','doctor.user','examType','branch','technician'])->withFileCounts()->orderByRaw("CASE workflow_status WHEN 'new' THEN 0 WHEN 'in_progress' THEN 1 ELSE 2 END")->latest()->limit(10)->get(); }
    #[Computed] public function byExamType() { return $this->query()->with('examType')->selectRaw('exam_type_id, count(*) as total')->groupBy('exam_type_id')->orderByDesc('total')->get(); }
    #[Computed] public function byBranch() { return $this->query()->with('branch')->selectRaw('branch_id, count(*) as total')->groupBy('branch_id')->orderByDesc('total')->get(); }
    #[Computed] public function doctorStats() { return $this->query()->with('doctor.user')->selectRaw('doctor_id, count(*) as total')->groupBy('doctor_id')->orderByDesc('total')->limit(8)->get(); }
    #[Computed] public function finance(): array { return auth()->user()->hasPermission(Permission::ViewFinancials) ? FinancialReport::summarize(auth()->user(),['from'=>today()->toDateString(),'to'=>today()->toDateString(),'branch'=>$this->branch]):[]; }
    #[Computed] public function visits(): array {
        if(!auth()->user()->hasPermission(Permission::ManageVisits)){return [];}
        $q=DoctorVisit::when(!auth()->user()->isAdmin(),fn($q)=>$q->whereIn('branch_id',AccessScope::branchIds(auth()->user())))->when($this->branch,fn($q)=>$q->where('branch_id',$this->branch));
        return ['month'=>(clone $q)->whereBetween('visited_at',[today()->startOfMonth()->toDateString(),today()->endOfMonth()->toDateString()])->count(),'overdue'=>(clone $q)->pendingFollowup()->where('next_visit_at','<',today()->toDateString())->count()];
    }
}; ?>
<div class="mx-auto w-full max-w-7xl space-y-5">
    <x-page-header title="لوحة التشغيل" :subtitle="now()->translatedFormat('l، j F Y').' — '.auth()->user()->name"><x-slot:actions>@if(auth()->user()->hasPermission(Permission::CreateCase))<flux:button variant="primary" icon="plus" :href="route('cases.create')" wire:navigate>حالة جديدة</flux:button>@endif</x-slot:actions></x-page-header>
    @if(auth()->user()->isAdmin())<flux:select wire:model.live="branch" label="الفرع" class="max-w-xs"><flux:select.option value="">جميع الفروع</flux:select.option>@foreach(AccessScope::branches(auth()->user())->get() as $b)<flux:select.option :value="(string)$b->id">{{ $b->name }}</flux:select.option>@endforeach</flux:select>@elseif(!auth()->user()->branch_id)<flux:callout color="amber">يحتاج حسابك إلى تحديد فرع من صفحة المستخدمين قبل بدء العمل.</flux:callout>@endif
    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(['today'=>'حالات اليوم','new'=>'الحالات الجديدة','in_progress'=>'قيد التنفيذ','completed'=>'الحالات المكتملة'] as $key=>$label)<x-stat-card :label="$label" :value="$this->stats[$key]" icon="folder-open" :href="route('cases.index',['branch'=>$branch,'workflow'=>$key==='today' ? '' : $key,'from'=>$key==='today' ? today()->toDateString():'','to'=>$key==='today' ? today()->toDateString():''])" />@endforeach</div>
    <x-panel title="متابعة الحالات" subtitle="الجديدة وقيد التنفيذ أولًا" :padded="false"><x-slot:actions><flux:button size="sm" variant="ghost" :href="route('cases.index')" wire:navigate>كل الحالات</flux:button></x-slot:actions><div class="divide-y">@forelse($this->recentCases as $case)<a href="{{ route('cases.show',$case) }}" wire:navigate class="flex min-h-20 flex-wrap items-center gap-4 px-5 py-4 hover:bg-brand-50/50"><div class="min-w-0 flex-1"><div class="font-semibold">{{ $case->patient->name }}</div><div class="mt-1 text-sm text-zinc-600">{{ $case->case_code }} · {{ $case->examType?->name ?? 'لم يحدد الفحص' }} · {{ $case->branch->name }}</div></div><div class="text-sm text-zinc-600">{{ $case->technician?->name ?? 'الفني لم يحدد' }}</div><flux:badge :color="$case->workflow_status->color()">{{ $case->workflow_status->label() }}</flux:badge><span class="text-sm text-zinc-600">{{ $case->fileCount(\App\Enums\CaseFileType::Report)+$case->fileCount(\App\Enums\CaseFileType::Image) }} صورة / تقرير</span></a>@empty<x-empty-state icon="folder-open" title="لا توجد حالات" text="ابدأ بتسجيل حالة جديدة." />@endforelse</div></x-panel>
    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(['total'=>'إجمالي الحالات','patients'=>'عدد المرضى','users'=>'عدد المستخدمين','doctors'=>'الأطباء النشطون'] as $key=>$label)<x-stat-card :label="$label" :value="$this->stats[$key]" icon="chart-bar" />@endforeach</div>
    <div class="grid gap-5 lg:grid-cols-2"><x-panel title="الحالات حسب الفرع"><div class="divide-y">@foreach($this->byBranch as $row)<div class="flex justify-between py-3 text-sm"><span>{{ $row->branch->name }}</span><strong>{{ $row->total }}</strong></div>@endforeach</div></x-panel><x-panel title="الحالات حسب نوع الفحص"><div class="divide-y">@foreach($this->byExamType as $row)<div class="flex justify-between py-3 text-sm"><span>{{ $row->examType?->name ?? 'الفحص لم يحدد' }}</span><strong>{{ $row->total }}</strong></div>@endforeach</div></x-panel></div>
    <x-panel title="إحصائيات الأطباء"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach($this->doctorStats as $row)<div class="rounded-lg bg-zinc-50 p-3"><div class="text-sm">{{ $row->doctor?->display_name ?? 'بدون طبيب محدد' }}</div><div class="mt-2 font-semibold">{{ $row->total }} حالة</div></div>@endforeach</div></x-panel>
    @if($this->visits)<x-panel title="زيارات الأطباء"><div class="flex flex-wrap gap-5 text-sm"><span>{{ $this->visits['month'] }} زيارة هذا الشهر</span><span>{{ $this->visits['overdue'] }} موعد متأخر</span><a class="text-brand-700 underline" href="{{ route('visits.index') }}" wire:navigate>متابعة الزيارات</a></div></x-panel>@endif
    @if($this->finance)<x-panel title="ملخص حسابات اليوم"><div class="grid gap-4 sm:grid-cols-3">@foreach($this->finance['currencies'] as $currency=>$row)<div><div class="text-sm text-zinc-500">المقبوض — {{ $currency }}</div><div class="mt-2 text-xl font-semibold">{{ Money::display((int)$row['collected']) }}</div><div class="mt-1 text-sm text-zinc-600">قيمة الفحوصات {{ Money::display((int)$row['billed']) }} · خصومات {{ Money::display((int)$row['discount']) }}</div></div>@endforeach</div><a class="mt-4 inline-block text-sm text-brand-700 underline" href="{{ route('accounts.index') }}" wire:navigate>فتح الحسابات</a></x-panel>@endif
</div>
