<?php
use App\Models\{ExamType,Branch};
use App\Support\{ActivityLogger,Money};
use Flux\Flux;
use Illuminate\Validation\Rule;
use Livewire\Attributes\{Computed,Locked,Title};
use Livewire\Component;
new #[Title('أنواع الفحوصات')] class extends Component {
    #[Locked] public ?int $editingId=null;
    public string $name=''; public string $category='2D'; public int $sort=0; public bool $is_active=true; public string $price=''; public string $description=''; public array $branchPrices=[]; public array $branchEnabled=[];
    public function boot(): void { abort_unless(auth()->user()->isAdmin(),403); }
    #[Computed] public function examTypes() { return ExamType::ordered()->withCount('cases')->get(); }
    public function create(): void { $this->resetForm(); Flux::modal('exam-form')->show(); }
    public function edit(int $id): void { $type=ExamType::with('branches')->findOrFail($id); $this->resetForm(); $this->editingId=$id; $this->fill($type->only('name','category','sort','is_active','description')); $this->description=(string)$type->description; $this->price=Money::decimal($type->base_price_minor); foreach($type->branches as $branch){$this->branchPrices[$branch->id]=Money::decimal($branch->pivot->base_price_minor);$this->branchEnabled[$branch->id]=(bool)$branch->pivot->is_active;} Flux::modal('exam-form')->show(); }
    public function save(): void {
        $data=$this->validate(['name'=>['required','string','max:100',Rule::unique('exam_types','name')->ignore($this->editingId)],'category'=>['required','in:2D,3D'],'sort'=>['required','integer','min:0','max:1000'],'is_active'=>['boolean'],'price'=>['nullable','string'],'description'=>['nullable','string','max:3000'],'branchPrices'=>['array'],'branchPrices.*'=>['nullable','string'],'branchEnabled'=>['array'],'branchEnabled.*'=>['boolean']]);
        if(($this->price!=='' || collect($this->branchPrices)->filter()->isNotEmpty()) && ! \App\Models\Setting::get('currency')) { $this->addError('price','حدد العملة من إعدادات المركز أولًا.'); return; }
        \Illuminate\Support\Facades\DB::transaction(function() use($data){$type=$this->editingId ? ExamType::findOrFail($this->editingId):new ExamType; $before=$type->toArray();$type->fill(['name'=>$data['name'],'category'=>$data['category'],'sort'=>$data['sort'],'is_active'=>$data['is_active'],'description'=>$data['description'] ?: null,'base_price_minor'=>$data['price']==='' ? null:Money::minor($data['price'])])->save();$pivot=[];foreach(Branch::all() as $branch){$price=$this->branchPrices[$branch->id] ?? ''; $pivot[$branch->id]=['base_price_minor'=>$price==='' ? null:Money::minor($price),'is_active'=>$this->branchEnabled[$branch->id] ?? true];}$type->branches()->sync($pivot);ActivityLogger::log('exam.updated',$type,['before'=>$before,'after'=>$type->toArray(),'branch_prices'=>$pivot]);});
        Flux::modal('exam-form')->close(); Flux::toast(text:'تم حفظ الفحص وأسعار الفروع.'); $this->resetForm();
    }
    public function delete(int $id): void { $type=ExamType::findOrFail($id); if($type->cases()->withTrashed()->exists()){Flux::toast(variant:'danger',text:'هذا الفحص مستخدم. يمكنك إيقافه بدلًا من حذفه.');return;} \Illuminate\Support\Facades\DB::transaction(function() use($type){ActivityLogger::log('exam.deleted',$type);$type->delete();}); }
    private function resetForm(): void { $this->reset('editingId','name','category','sort','is_active','price','description','branchPrices','branchEnabled'); $this->resetValidation(); }
}; ?>
<div class="mx-auto w-full max-w-5xl"><x-page-header title="أنواع الفحوصات" subtitle="سعر أساسي للفحص، مع أسعار وتفعيل مستقلين لكل فرع"><x-slot:actions><flux:button variant="primary" icon="plus" wire:click="create">إضافة نوع فحص</flux:button></x-slot:actions></x-page-header><x-panel :padded="false"><div class="divide-y">@foreach($this->examTypes as $type)<div class="flex flex-wrap items-center gap-4 p-4"><div class="min-w-0 flex-1"><strong>{{ $type->name }}</strong><p class="mt-1 text-sm text-zinc-600">{{ $type->description }} · {{ $type->cases_count }} حالة</p></div><span>{{ Money::display($type->base_price_minor) }} {{ \App\Models\Setting::get('currency') }}</span><flux:badge :color="$type->is_active ? 'green':'zinc'">{{ $type->is_active ? 'مفعّل':'متوقف' }}</flux:badge><flux:button size="sm" wire:click="edit({{ $type->id }})">تعديل</flux:button><flux:button size="sm" variant="ghost" wire:click="delete({{ $type->id }})" wire:confirm="حذف هذا الفحص؟">حذف</flux:button></div>@endforeach</div></x-panel>
<flux:modal name="exam-form" class="w-full max-w-2xl"><form wire:submit="save" class="space-y-4"><flux:heading size="lg">بيانات الفحص</flux:heading><flux:input wire:model="name" label="اسم الفحص" /><div class="grid gap-3 sm:grid-cols-3"><flux:input wire:model="price" label="السعر الأساسي" inputmode="decimal" /><flux:select wire:model="category" label="الفئة"><flux:select.option value="2D">2D</flux:select.option><flux:select.option value="3D">3D</flux:select.option></flux:select><flux:input wire:model="sort" label="الترتيب" type="number" min="0" /></div><flux:textarea wire:model="description" label="الوصف (اختياري)" rows="2" /><flux:switch wire:model="is_active" label="الفحص مفعّل" /><div class="space-y-4 border-t pt-4"><flux:heading>الأسعار حسب الفرع</flux:heading>@foreach(Branch::all() as $branch)<div class="grid items-center gap-3 sm:grid-cols-2"><flux:input wire:model="branchPrices.{{ $branch->id }}" :label="$branch->name.' — السعر'" description="فارغ = استخدام السعر الأساسي" inputmode="decimal" /><flux:select wire:model="branchEnabled.{{ $branch->id }}" :label="'التفعيل في '.$branch->name"><flux:select.option value="1">مفعّل</flux:select.option><flux:select.option value="0">متوقف</flux:select.option></flux:select></div>@endforeach</div><flux:button type="submit" variant="primary">حفظ الفحص</flux:button></form></flux:modal></div>
